reaper_hostname: 127.0.0.1
reaper_port: 8000
listen_ip: 0.0.0.0
osc_port: 9002
http_port: 8080
broadcast_ip: 172.25.19.255
video_port: 12339
info_port: 12340
system:
  - name: RE01
    ip: 172.25.18.201
    user: avm
    services:
      - seamless_jack
      - osc-kreuz
      - cwonder
      - aj-snapshot
      - sc_mix
      - ambdec_3rd
      - ambdec_rev
  - name: RE02
    ip: 172.25.18.202
    user: avm
    services:
      - seamless_jack
      - twonder
      - aj-snapshot
      - sc_wfs
  - name: RE03
    ip: 172.25.18.203
    user: avm
    services:
      - seamless_jack
      - twonder
      - aj-snapshot
      - sc_wfs
  - name: syncplayer-01
    ip: 3910-PC-01
    user: avm
    services:
      - mpv
  - name: syncplayer-02
    ip: 3910-PC-02
    user: avm
    services:
      - mpv
  - name: syncplayer-03
    ip: 3910-PC-03
    user: avm
    services:
      - mpv
  - name: syncplayer-04
    ip: 3910-PC-04
    user: avm
    services:
      - mpv
  - name: syncplayer-05
    ip: 3910-PC-05
    user: avm
    services:
      - mpv
  - name: syncplayer-06
    ip: 3910-PC-06
    user: avm
    services:
      - mpv
  - name: syncplayer-07
    ip: 3910-PC-07
    user: avm
    services:
      - mpv
  - name: syncplayer-08
    ip: 3910-PC-08
    user: avm
    services:
      - mpv
