- command: 'play'
  time: 2021-09-6 12:20:00
  audio_index: 1
  video_index: 1
- command: 'play'
  time: 2021-09-6 12:20:05
  audio_index: 2
  video_index: 2
- command: 'play'
  time: 2021-09-6 12:20:10
  audio_index: 3
  video_index: 3
