- command: 'play'
  day_of_week: 0
  hour: 14
  minute: 10
  audio_index: 1
  video_index: 1
- command: 'play'
  day_of_week: 0
  hour: 14
  minute: 10
  audio_index: 2
  video_index: 2
- command: 'play'
  day_of_week: 0
  hour: 14
  minute: 10
  audio_index: 3
  video_index: 3
