- command: 'play'
  day_of_week: '0,1,2,3,4,5,6'
  hour: 10,11,12,13,14,15,16,17,18,19
  minute: 0
  second: 0
  audio_index: 1
  video_index: 0
- command: 'play'
  day_of_week: '0,1,2,3,4,5,6'
  hour: 10,11,12,13,14,15,16,17,18,19
  minute: 3
  second: 20
  audio_index: 2
  video_index: 1
- command: 'play'
  day_of_week: '0,1,2,3,4,5,6'
  hour: 10,11,12,13,14,15,16,17,18,19
  minute: 19
  second: 50
  audio_index: 3
  video_index: 2
- command: 'play'
  day_of_week: '0,1,2,3,4,5,6'
  hour: 10,11,12,13,14,15,16,17,18,19
  minute: 39
  second: 15
  audio_index: 1
  video_index: 0
- command: 'play'
  day_of_week: '0,1,2,3,4,5,6'
  hour: 10,11,12,13,14,15,16,17,18,19
  minute: 42
  second: 45
  audio_index: 4
  video_index: 3

