id: iwillnotweep
title_de: I Will Not Weep
title_en: I Will Not Weep
artist: Senti Toy Threadgill
audio_index: 6
video_index: 4
duration:
  minutes: 19
  seconds: 30
description: |
  “No one can take the song within me
  No one can take the song within
  I Will Not Weep”
  
  Die wassergetränkten Reisterrassen von Nagaland, dem Kernland, in dem die elementaren Klänge von Wasser, feuchter Erde, Schweiß, Atem und menschlicher Stimme ein Lied finden. „I Will Not Weep“ ist ein Lied der Widerstandsfähigkeit. Es ist die gleichzeitige Vielfalt der Naga-Klänge mit ihrer komplexen kolonialen Vergangenheit und der allgegenwärtigen, zerstörerischen Gewalt der indischen Armee. Die Naga haben im Laufe der Zeit viel getrauert und verloren, aber wir singen.
description_en: |
  “No one can take the song within me
  No one can take the song within
  I Will Not Weep”

  The water terrace rice fields of Nagaland, the heartland where elemental sounds of water, wet earth, sweat, breath, and the human voice find song. “I Will Not Weep” is a song of resilience. It is the simultaneous plurality of Naga sounds with its complex colonized past, and the ever present disruptive violence of the Indian army. There has been deep mourning and loss over time for the Nagas, but we sing.